# Default Skiko CI
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          distribution: 'adopt'
          java-version: '17'
      - shell: bash
        run: |
          ./gradlew buildPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: skikomirai
          path: ./build/mirai
          retention-days: 5
      - name: Release
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: releases
          FOLDER: ./build/mirai
