# Default Skiko CI
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1.4.3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - shell: bash
        run: |
          ./gradlew buildPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: skikomirai-windows
          path: ./build/mirai
          retention-days: 5
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{steps.branch_name.outputs.SOURCE_TAG}}
          prerelease: false
          title: ${{steps.branch_name.outputs.SOURCE_TAG}}
          files: |
            build/mirai/*.jar

   macos:
     runs-on: macos-11
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-java@v1.4.3
         with:
           distribution: 'adopt'
           java-version: '17'
       - shell: bash
         run: |
           chmod +x gradlew
           ./gradlew buildPlugin
           mv ./build/mirai/*.jar ./
       - uses: actions/upload-artifact@v2
         with:
           name: skikomirai-macos
           path: ./build/mirai
           retention-days: 5
       -  uses: jasondavis303/tag-and-release-and-upload@v1.2.0
          with:
           github-token: ${{ secrets.GITHUB_TOKEN }}

           version: ${{steps.branch_name.outputs.SOURCE_TAG}}
           assets: '[ "*.jar" ]'
           overwrite: false

   linux:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-java@v1.4.3
         with:
           distribution: 'adopt'
           java-version: '17'
       - shell: bash
         run: |
           chmod +x gradlew
           ./gradlew buildPlugin
       - uses: actions/upload-artifact@v2
         with:
           name: skikomirai-linux
           path: ./build/mirai
           retention-days: 5
       - uses: "marvinpinto/action-automatic-releases@latest"
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: ${{steps.branch_name.outputs.SOURCE_TAG}}
           prerelease: false
           title: ${{steps.branch_name.outputs.SOURCE_TAG}}
           files: |
             build/mirai/*.jar
   linuxArm64:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-java@v1.4.3
         with:
           distribution: 'adopt'
           java-version: '17'
           architecture: aarch64
       - shell: bash
         run: |
           chmod +x gradlew
           ./gradlew buildPlugin
       - uses: actions/upload-artifact@v2
         with:
           name: skikomirai-linuxArm64
           path: ./build/mirai
           retention-days: 5
       - uses: "marvinpinto/action-automatic-releases@latest"
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: ${{steps.branch_name.outputs.SOURCE_TAG}}
           prerelease: false
           title: ${{steps.branch_name.outputs.SOURCE_TAG}}
           files: |
             build/mirai/*.jar